const products={
  'kit-complet':{name:'Kit complet pentru restaurări dentare',category:'KIT DE PRACTICĂ',price:450,images:['kit-restaurari.png','kit-restaurari-2.png','kit-restaurari-3.png'],intro:'Tot ce ai nevoie pentru a transforma practica de restaurare într-un ritual simplu și constant.',details:['5 modele 3D','instrumente pentru modelaj','pene și matrici','benzi abrazive','compozit fotopolimerizabil','lampă mini UV','cartea pentru dexteritate inclusă'],note:'Ideal dacă vrei să începi organizat, cu resursele esențiale într-un singur kit.'},
  'clasa-i-maxilar':{name:'Restaurări clasa I — maxilar',category:'MODELE PENTRU RESTAURĂRI',images:['restaurari-clasa-i-maxilar.png'],intro:'Un model anatomic pentru a exersa restaurările clasa I pe maxilar, în propriul ritm.',details:['relief anatomic clar și ușor de urmărit','potrivit pentru sesiuni de practică repetate','alege pachetul potrivit pentru tine'],note:'Începe cu o piesă sau alege un pachet avantajos pentru mai mult exercițiu.'},
  'clasa-i-mandibula':{name:'Restaurări clasa I — mandibulă',category:'MODELE PENTRU RESTAURĂRI',images:['restaurari-clasa-i-mandibula.png'],intro:'Un model dedicat restaurărilor clasa I pe mandibulă, creat pentru o practică mai sigură și mai coerentă.',details:['anatomie potrivită pentru exercițiu țintit','util pentru dezvoltarea dexterității','disponibil individual sau în pachete'],note:'Repetiția îți construiește controlul — alege cantitatea care se potrivește planului tău de practică.'},
  'clasa-ii-maxilar':{name:'Restaurări clasa a II-a — maxilar',category:'MODELE PENTRU RESTAURĂRI',images:['restaurari-clasa-ii-maxilar.png'],intro:'Exersează restaurările clasa a II-a pe maxilar cu un model construit pentru atenție la fiecare detaliu.',details:['spații de lucru clare pentru exerciții precise','sprijină învățarea pas cu pas','potrivit pentru practică individuală'],note:'Un model de lucru simplu, pentru mai multă siguranță în fiecare mișcare.'},
  'clasa-ii-mandibula':{name:'Restaurări clasa a II-a — mandibulă',category:'MODELE PENTRU RESTAURĂRI',images:['restaurari-clasa-ii-mandibula.png'],intro:'Un model de practică pentru restaurările clasa a II-a pe mandibulă, pentru progres calm și repetabil.',details:['detalii anatomice utile pentru exerciții','pentru practică de precizie și control','pachete pentru sesiuni de exercițiu recurente'],note:'Alege pachetul de care ai nevoie și fă din practică o rutină constantă.'},
  dexteritate:{name:'Dexteritate & lucru în oglindă',category:'CARTE DE PRACTICĂ',price:79,images:['ebook-dexteritate.png'],intro:'O carte tipărită care te ghidează prin exerciții de precizie, coordonare și lucru în oglindă.',details:['50 de pagini de exerciții practice','pentru control, simetrie și răbdare','ușor de integrat în rutina ta'],note:'O resursă potrivită pentru cei care vor să transforme exercițiul într-un obicei.'}
};
const packs=[{label:'1 bucată',price:30},{label:'3 bucăți',price:75},{label:'6 bucăți',price:150}];
const id=new URLSearchParams(location.search).get('id'),product=products[id]||products['kit-complet'],root=document.getElementById('product-content'),toast=document.querySelector('.toast'),CART_KEY='empattydent_cart_v1';
let chosen=product.price?{label:'',price:product.price}:packs[0];
document.title=`${product.name} — Empatty Dent`;
root.innerHTML=`<div class="detail-gallery">${product.images.map((image,index)=>`<img class="${index===0?'active':''}" src="assets/${image}" alt="${product.name}" />`).join('')}</div><div class="detail-copy"><p class="eyebrow">${product.category}</p><h1>${product.name}</h1><p class="detail-intro">${product.intro}</p><ul>${product.details.map(detail=>`<li>${detail}</li>`).join('')}</ul>${product.price?'':`<label class="detail-select-label">Alege cantitatea<select id="detail-pack">${packs.map((pack,index)=>`<option value="${index}">${pack.label} — ${pack.price} lei</option>`).join('')}</select></label>`}<p class="detail-note">${product.note}</p><div class="detail-buy"><strong id="detail-price">${chosen.price} lei</strong><button class="btn primary" id="detail-add">Adaugă în coș <span>→</span></button></div><p class="delivery-note">Plata se face ramburs. Produsele sunt pregătite pentru expediere după confirmarea comenzii.</p></div>`;
const thumbnails=root.querySelectorAll('.detail-gallery img');thumbnails.forEach(image=>image.addEventListener('click',()=>{thumbnails.forEach(item=>item.classList.remove('active'));image.classList.add('active')}));
const packSelect=document.getElementById('detail-pack');if(packSelect)packSelect.addEventListener('change',()=>{chosen=packs[packSelect.value];document.getElementById('detail-price').textContent=`${chosen.price} lei`});
function renderCount(){const cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]');document.querySelector('.cart-count').textContent=cart.reduce((sum,item)=>sum+item.qty,0)}
document.getElementById('detail-add').addEventListener('click',()=>{const cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]'),name=`${product.name}${chosen.label?` (${chosen.label})`:''}`,existing=cart.find(item=>item.name===name);if(existing)existing.qty++;else cart.push({name,price:chosen.price,qty:1});localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCount();toast.textContent='Produs adăugat în coș';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)});renderCount();
